export const ADD_EMAIL = 'ADD_EMAIL';
export const RESET_EMAIL = 'RESET_EMAIL';
export const EMAIL_LOADING = 'EMAIL_LOADING';
export const EMAIL_FAILED = 'EMAIL_FAILED';
export const RESET_EMAIL_ERROR = 'RESET_EMAIL_ERROR';

export const MODAL_OFF = 'MODAL_OFF';

export const ADD_NEWUSER = 'ADD_NEWUSER';
export const NEWUSER_LOADING = 'NEWUSER_LOADING';
export const NEWUSER_FAILED = 'NEWUSER_FAILED';

export const ADD_REWARDS = 'ADD_REWARDS';
export const RESET_REWARD = 'RESET_REWARD';
export const REWARDS_LOADING = 'REWARDS_LOADING';
export const REWARDS_FAILED = 'REWARDS_FAILED';